### ISSUE TITLE
Scheduler-builder output wrong results

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#1518]
#### What happened:
when having the schedule yaml with two patch releases but the next schedule is not the same as the last patch release it generate duplicate results for the markdown

for example we have the following schedule.yaml
```yaml
schedules:
- release: 1.19
  next: 1.19.1
  cherryPickDeadline: 2020-09-04
  targetDate: 2020-09-09
  endOfLifeDate: 2021-09-30
  previousPatches:
    - release: 1.19.2
      cherryPickDeadline: 2020-09-11
      targetDate: 2020-09-16
    - release: 1.19.1
      cherryPickDeadline: 2020-09-04
      targetDate: 2020-09-09
```

it outputs
```
### Timeline

### 1.19

Next patch release is **1.19.1**

End of Life for **1.19** is **2021-09-30**

| PATCH RELEASE | CHERRY PICK DEADLINE | TARGET DATE |
|---------------|----------------------|-------------|
| 1.19.1        | 2020-09-04           | 2020-09-09  |
| 1.19.2        | 2020-09-11           | 2020-09-16  |
| 1.19.1        | 2020-09-04           | 2020-09-09  |

```

but the correct output should be 
```
### Timeline

### 1.19

Next patch release is **1.19.1**

End of Life for **1.19** is **2021-09-30**

| PATCH RELEASE | CHERRY PICK DEADLINE | TARGET DATE |
|---------------|----------------------|-------------|
| 1.19.2        | 2020-09-11           | 2020-09-16  |
| 1.19.1        | 2020-09-04           | 2020-09-09  |
```

issue reported in this PR: https://github.com/kubernetes/sig-release/pull/1210#issuecomment-685958560
 
/kind bug
