### ISSUE TITLE
Freezing k8s.gcr.io implementation details

### ISSUE THREAD

**Issue by upodroid** [kubernetes/release#2947]
KEP: https://github.com/kubernetes/enhancements/issues/3720

/cc @kubernetes/release-engineering @dims @ameukam 

This issue is about the release tooling changes to effectively freeze the old registry. Infra changes are being handled separately.

This is a typical image manifest: https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/manifests/k8s-staging-addon-manager/promoter-manifest.yaml

```
registries:
- name: gcr.io/k8s-staging-addon-manager
  src: true
- name: us.gcr.io/k8s-artifacts-prod/addon-manager
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/addon-manager
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/addon-manager
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-east1-docker.pkg.dev/k8s-artifacts-prod/images/addon-manager
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-south1-docker.pkg.dev/k8s-artifacts-prod/images/addon-manager
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
... MORE AR ENTRIES
```

For the old image registry freeze to take effect, all the `*.gcr.io/k8s-artifacts-prod/*` entries must be deleted and replaced with a single entry called `gcr.io/k8s-artifacts-prod/*`(this is a private GCR registry). This new entry will be used for copying image layers to s3 till @BenTheElder's tool geranos is ready for prod. I'm also using this opportunity to add 2 new US Artifact Registry regions.

There are some extra things I would like to do alongside this change.

- Clean up image promoter manifests for projects that never promote to registry.k8s.io (There are many)  https://github.com/kubernetes/k8s.io/pull/4808
- https://github.com/kubernetes/k8s.io/pull/4809
- Duplicate the content of `k8s.gcr.io` folder in the k/k8s.io registry and move it to `registry.k8s.io` folder

We have two options:

1. We can remove the the gcr.io entries from existing manifests before 3rd of April and call it a day. We'll fix kpromo and our release tooling after 1.27 is cut. This is not my recommended option but we might have to do this if we run into bugs with our release process(like the failed release in February) or poor availability from SIG Release TLs/Chairs
2. Update promo-tools. The exact steps are in the KEP https://github.com/kubernetes/enhancements/pull/3723/files#diff-698f06c1d84d830d9f77401818abd89534ca60dd9c732d2a491b88518b6d78f6R113
