### ISSUE TITLE
The repository 'https://pkgs.k8s.io kubernetes-xenial InRelease' is not signed

### ISSUE THREAD

**Issue by xqi-nr** [kubernetes/release#3524]
### What happened?

I am trying to update the old apt repo to the new apt repo (pkgs.k8s.io) in my Ansible workflow

```
- name: Create k8s apt repo key folder
  shell:
    cmd: sudo mkdir -p /etc/apt/keyrings

- name: Download k8s apt repo key
  shell:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.25/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add ansible apt key from file
  ansible.builtin.apt_key:
    file: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

...

- name: Download k8s source list file
  shell:
    cmd: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.25/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

...

- name: Explicitly add apt-key
  shell:
    cmd: sudo apt-key add /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add the Kubernetes repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/ kubernetes-xenial main"
    update_cache: True
    state: present
    mode: 0644
    filename: kubernetes
```

I got the following error (I redact my IP)

```
TASK [kubernetes : Add the Kubernetes repo] ************************************
fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://pkgs.k8s.io/dists/kubernetes-xenial/InRelease  403  Forbidden [IP: XXX.XXX.XXX.XXX 443], E:The repository 'https://pkgs.k8s.io/ kubernetes-xenial InRelease' is not signed."}
```

### What did you expect to happen?

The `update apt cache` passes.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the Ansible actions I mention above in the description.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
Ubuntu 20_04-lts-gen2

-> SourceImageName: '/subscriptions/********/providers/Microsoft.Compute/locations/eastus/publishers/Canonical/ArtifactTypes/vmimage/offers/0001-com-ubuntu-server-focal/skus/20_04-lts-gen2/versions/latest'

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
